server:
  port: 8888  # Config Server 포트

spring:
  application:
    name: config-server
  profiles:
    active: native  # 파일 시스템 기반 설정 사용 (Git도 가능)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config  # 설정 파일 위치

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
