server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql-order:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example: DEBUG
    com.example.order.client: DEBUG
    feign: DEBUG

# 추가 설정: 비즈니스 로직 관련
app:
  order:
    max-order-amount: 1000000
    delivery-fee: 3000

# Distributed Tracing - Zipkin
management:
  tracing:
    sampling:
      probability: 1.0  # 100% 샘플링 (개발 환경, 운영에서는 0.1 권장)
    propagation:
      type: b3  # Zipkin B3 propagation format
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# Resilience4j Circuit Breaker 설정 (서비스 간 호출용)
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      userClient:  # Feign Client 이름
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      userClient:
        baseConfig: default
